apiVersion: apps/v1
kind: Deployment
metadata:
  name: app22
  labels:
    app: app22
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app22
  template:
    metadata:
      labels:
        app: app22
    spec:
      containers:
      - name: app22
        image: teymurgahramanov/app22
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app22
  labels:
    app: app22
spec:
  selector:
    app: app22
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000