apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: app22
build:
  local:
    push: false
  artifacts:
    - image: app22-dev
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: app22-dev
        namespace: app22-dev
        createNamespace: true
        chartPath: ./helm
        setValueTemplates:
          image.repository: "{{ .IMAGE_REPO_app22-dev }}"
          image.tag: "{{ .IMAGE_TAG_app22-dev }}"
profiles:
  - name: local
    activation:
      - kubeContext: local
        command: dev