apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: app22
build:
  tagPolicy:
    inputDigest: {}
  local:
    push: true
  artifacts:
    - image: app22
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: app22
        namespace: app22-dev
        createNamespace: true
        chartPath: ./helm
        setValueTemplates:
          image.repository: "{{ .IMAGE_REPO_app22 }}"
          image.tag: "{{ .IMAGE_TAG_app22 }}"

portForward:
- resourceType: deployment
  resourceName: app22
  namespace: app22-dev
  port: 5000
  localPort: 9500

profiles:
  - name: local
    activation:
      - kubeContext: local
        command: dev