image:
  repository: teymurgahramanov/app22
  tag: ""
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 5000
  # NodePort configuration - only used when type is NodePort
  nodePort: 30000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []
