name: PR

on:
  push:
    branches-ignore:
      - master
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest