name: PR

on:
  push:
    branches-ignore:
      - master
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: test-code
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pytest
      - name: test-build
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: app22