name: PR

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          pytest