name: Create release

on:
  workflow_dispatch:
    inputs:
      release-name:
        type: string
        description: Release name
        required: true

env:
  IMAGE_NAME: ${{ github.repository }}
  HELM_REPO_NAME: charts
  HELM_REPO_OWNER: ${{ secrets.HELM_REPO_OWNER }}
  HELM_REPO_TOKEN: ${{ secrets.HELM_REPO_TOKEN }}
  RELEASE_VERSION: ${{ github.event.inputs.release-name }}
  CHART_FILE: helm/Chart.yaml

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}, ${{ env.IMAGE_NAME }}:latest

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Update Chart.yaml and package
        run: |
          APP_VERSION="$RELEASE_VERSION"
          echo "Updating $CHART_FILE with appVersion=$APP_VERSION"
          sed -i "s/^appVersion:.*/appVersion: \"$APP_VERSION\"/" $CHART_FILE
          mkdir -p packaged
          helm dependency update helm/
          helm package helm/ --destination packaged

      - name: Push Helm chart
        run: |
          git clone -b gh-pages --depth 1 https://${{ env.HELM_REPO_OWNER }}:${{ env.HELM_REPO_TOKEN }}@github.com/${{ env.HELM_REPO_OWNER }}/${{ env.HELM_REPO_NAME }}.git helm-charts
          mv -f packaged/*.tgz helm-charts/
          cd helm-charts
          helm repo index . --url https://${{ env.HELM_REPO_OWNER }}.github.io/${{ env.HELM_REPO_NAME }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🆕 Publish chart for release {{ github.repository_name }} ${{ github.event.release.tag_name }}"
          git push

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ inputs.release-name }}
          tag: ${{ inputs.release-name }}
          bodyFile: RELEASE_NOTES.md
          allowUpdates: true
          artifactErrorsFailBuild: true
          makeLatest: true

      - name: Bump Helm chart version
        id: bump
        run: |
          CURRENT_CHART_VERSION=$(grep '^version:' $CHART_FILE | cut -d' ' -f2)
          NEW_CHART_VERSION=$(echo $CURRENT_CHART_VERSION | awk -F. -v OFS=. '{$NF += 1 ; print}')
          sed -i "s/^version:.*/version: $NEW_CHART_VERSION/" $CHART_FILE
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $CHART_FILE
          git commit -m "⬆️ Bump Helm chart to $NEW_CHART_VERSION"
          git push
