name: Release

on:
  workflow_dispatch:
    inputs:
      release-name:
        type: string
        description: Release name
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ github.repository }}:${{ inputs.release-name }},${{ github.repository }}:latest

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ inputs.release-name }}
          tag: ${{ inputs.release-name }}
          body: ""
          allowUpdates: true
          artifactErrorsFailBuild: true
          makeLatest: true
